version: '3.1'
volumes:
  pg:
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=timeweb
      - POSTGRES_USER=timeweb
      - POSTGRES_DB=timeweb
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - 5536:5536
