services:
  nuxt_green:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres_green
    restart: always
    volumes:
      - ./uploaded:/green/uploaded

  postgres_green:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: green
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: greenbabyportfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-green:/var/lib/postgresql/data

volumes:
  postgres-data-green:
