name: Deploy

on:
  push:

jobs:
  deploy: # деплой на prod сервер
    # на сервер выкладываем только ветку main
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    # выкладываем, только если проверка успешна
    steps:
      - uses: actions/checkout@v3
      - name: Add ssh key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Deploy project
        env:
          options: ssh -i ~/.ssh/key -o StrictHostKeyChecking=no
        run: |
          rsync -e "$options" -avzpg . '${{secrets.USER}}@${{secrets.HOST}}:${{secrets.WWW}}'
          ssh -i ~/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.WWW }} \
          && npm i \
          && npm run build \
          && pm2 start"
